apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workout-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: http://192.168.0.21/
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80